# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-02-06 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_likecount_likerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='likerecord',
            name='user',
            field=models.CharField(default='abc', max_length=30),
            preserve_default=False,
        ),
    ]
