# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-03-01 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20200206_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
