# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-03-01 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_imgk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgk',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
