# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-04-11 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20200301_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcImgK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='keke')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
    ]
