# Generated by Django 3.0.2 on 2020-09-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='allclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tea2class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=100)),
                ('class_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='classes',
            new_name='class_id',
        ),
    ]
