# Generated by Django 3.0.1 on 2020-12-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_allclass_student_tea2class_tea2class23_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tea2class23',
        ),
    ]
