# Generated by Django 3.0.2 on 2020-10-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20200923_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea2class',
            name='class_id',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tea2class',
            name='teacher_id',
            field=models.IntegerField(max_length=100),
        ),
    ]
