# Generated by Django 3.0.1 on 2020-12-07 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_testdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='testinfo',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('age', models.IntegerField(default=1)),
                ('ug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.testdata')),
            ],
        ),
    ]
