# Generated by Django 3.0.1 on 2020-12-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_testinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testinfo',
            name='ug',
        ),
    ]
