# Generated by Django 3.0.1 on 2020-12-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_testinfo_ug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testinfo',
            name='ug',
        ),
        migrations.DeleteModel(
            name='testdata',
        ),
        migrations.DeleteModel(
            name='testinfo',
        ),
    ]
