# Generated by Django 3.0.1 on 2020-12-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_auto_20201211_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Love',
        ),
    ]
