# Generated by Django 3.0.1 on 2020-12-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_delete_love'),
    ]

    operations = [
        migrations.AddField(
            model_name='boy',
            name='m',
            field=models.ManyToManyField(to='User.Girl'),
        ),
    ]
