# Generated by Django 3.0.1 on 2020-12-15 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_boy_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Boy')),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Girl')),
            ],
            options={
                'unique_together': {('b', 'g')},
            },
        ),
    ]
