# Generated by Django 3.0.1 on 2020-12-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_auto_20201216_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boy',
            name='m',
        ),
    ]
