# Generated by Django 3.0.1 on 2020-12-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_auto_20201216_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='f',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='c_time',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
