# Generated by Django 3.0.1 on 2020-12-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_remove_userinfo_c_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='c_time',
            field=models.DateTimeField(null=True),
        ),
    ]
