# Generated by Django 3.0.1 on 2020-12-28 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0032_userinfo_c_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarryBoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MarryGirl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='color',
            field=models.IntegerField(choices=[(1, '黑色'), (2, '白色'), (3, '蓝色')], default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MarryB2G',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.MarryBoy')),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.MarryGirl')),
            ],
        ),
    ]
