# Generated by Django 3.0.1 on 2020-12-30 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0033_auto_20201228_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarryBoth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')])),
            ],
        ),
        migrations.CreateModel(
            name='U2U',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='girls', to='User.MarryBoth')),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boys', to='User.MarryBoth')),
            ],
        ),
    ]
